### ISSUE TITLE
/silos semble infonctionnel

### ISSUE THREAD

**Issue by AmauryCarrade** [Coutume/zBanque-WebServices#4]
J'ai une erreur 500 sur /silos avec [ce contenu](http://paste.carrade.eu/?c4dce424a9b83fad#Tcs8A8lyrrZg9T3SpGcaczj+W9YsP+oeSYpUaL8Hc3U=) envoyé en POST.

```
[15:14:16 ERROR]: [zBanque] Error while sending a PacketPlayOutSilos packet
[15:14:16 ERROR]: [zBanque] Exception : 
java.io.IOException: Server returned HTTP response code: 500 for URL: http://127.0.0.1:8088/silos
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_72]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_72]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_72]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_72]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1890) ~[?:1.8.0_72]
        at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1885) ~[?:1.8.0_72]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_72]
        at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1884) ~[?:1.8.0_72]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1457) ~[?:1.8.0_72]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_72]
        at fr.zcraft.zbanque.network.PacketSender.makeRequest(PacketSender.java:183) ~[?:?]
        at fr.zcraft.zbanque.network.PacketSender.access$000(PacketSender.java:56) ~[?:?]
        at fr.zcraft.zbanque.network.PacketSender$2.run(PacketSender.java:133) ~[?:?]
        at fr.zcraft.zbanque.network.PacketSender$2.run(PacketSender.java:123) ~[?:?]
        at fr.zcraft.zbanque.libs.fr.zcraft.zlib.components.worker.Worker.run(Worker.java:176) ~[?:?]
        at fr.zcraft.zbanque.libs.fr.zcraft.zlib.components.worker.Worker.access$000(Worker.java:47) ~[?:?]
        at fr.zcraft.zbanque.libs.fr.zcraft.zlib.components.worker.Worker$1.run(Worker.java:215) ~[?:?]
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://127.0.0.1:8088/silos
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840) ~[?:1.8.0_72]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[?:1.8.0_72]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_72]
        at fr.zcraft.zbanque.network.PacketSender.makeRequest(PacketSender.java:177) ~[?:?]
        ... 6 more
```

**Comment by Coutume** [comment]
Bonjour,
La position d'accès au silo (x et z) n'a pas été renseignée. JSON valide (mais raccourci) :  http://paste.carrade.eu/?23757aec2deb09d0#4mtplgPsrzNWaoXX5F9VuYLk2o000/uPx4Qge8yhc50=
Il faut par ailleurs renseigner la banque comme un objet `{[...]"banque" : {"nom" : "massive"}}`. Si c'est sa première insertion, toutes les propriétés des la banque doivent être renseignées (voir l'entité Banque).

**Comment by AmauryCarrade** [comment]
Hm, ça devient fonctionnel en corrigeant le JSON (il fallait aussi ajouter les coordonnées `x` et `z` de la sortie principale du silo) ; cela dit, à l'insertion, j'ai l'erreur suivante : 

```
An exception occurred while executing 'INSERT INTO items (idItem, data, nom) VALUES (?, ?, ?)' with params [4, 0, ""]:
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-0' for key 'item_idx'
```

(avec les même données qu'auparavant, en corrigeant les erreurs).

Au passage, cette requête retourne une erreur 400, alors que là, pour le coup, une erreur 500 serait requise :p (mais c'est plus du ressort de #5).

**Comment by Coutume** [comment]
Comme dis dans l'incident, une meilleure gestion des exceptions va venir. :)
Le JSON que je t'ai passé marche bien chez moi, tu peux m'envoyer le tiens stp ?

**Comment by AmauryCarrade** [comment]
C'est celui lié plus haut dans le premier message. Il y a des valeurs d'objet vide (pour les silos vides) et dupliqués (pour les silos contenant la même chose) qui semblent mal prise en compte (en particulier les secondes).

Pour les codes d'erreur c'est juste à titre indicatif, j'ai bien noté :) .

**Comment by Coutume** [comment]
Je n'arrive pas à reproduire l'erreur, le premier JSON posté ne marche pas à cause du manque des coordonnées et de la banque. :/

**Comment by AmauryCarrade** [comment]
Ah oui, zut. Je t'envoie un JSON correct de ce côté sous peu.

**Comment by AmauryCarrade** [comment]
[Voici un JSON qui “marche”](http://paste.carrade.eu/?3c1654ed89a265f2#kulfFNfTVfMBOzryR5jmhAjG/IqqacQSbqYmExwo4bM=) (qui est correctement interprêté en terme d'entités, disons).

**Comment by Coutume** [comment]
Bon, après investigation il se trouve que Doctrine ne permet pas de récupérer des entités "persistées" - mais non insérées en base de données - par les Repository(s).
Le dernier commit devrait régler ce problème, néanmoins il entraine une baisse des performances...
Dis-moi si c'est OK chez toi.

**Comment by AmauryCarrade** [comment]
C'est OK. Long, mais OK.
